"""Tests for the Phase 1G hybrid RRF retrieval baseline.

All tests here are fast, deterministic, and offline: components are
stub retrievers (or a ``DenseRetriever`` on a fake encoder) injected
through ``component_factory``, so no sentence-transformers model is
loaded and no network is touched. The real pinned-model hybrid smoke
lives in ``test_hybrid_integration.py`` (``@pytest.mark.integration``).

The exact-RRF expected values below are hand-computed from the frozen
formula ``RRF(d) = Σ_i 1 / (rrf_k + rank_i(d))`` and written as
numeric literals — they are never generated by calling the production
fusion helper.
"""

from __future__ import annotations

import copy
import subprocess
import sys

import pytest

from commercebench.contracts import (
    SCHEMA_VERSION,
    Answerability,
    CaseSpec,
    ContractValidationError,
    ConversationType,
    Difficulty,
    EvaluationResult,
    ExperimentManifest,
    RetrievalConfig,
    RunTrace,
)
from commercebench.evaluation import (
    FAILURE_RETRIEVAL_MISS,
    DeterministicRAGEvaluator,
)
from commercebench.rag import (
    BM25Retriever,
    Corpus,
    DenseRetriever,
    DeterministicRAGPipeline,
    Document,
    HybridRRFRetriever,
    RetrievalResult,
    Retriever,
    SentenceTransformerEncoder,
    build_retriever,
)
from commercebench.runner import run_case
from commercebench.systems import DeterministicRAGSystem

SPARSE_ID = "bm25-okapi-v0"
DENSE_ID = "dense-minilm-l6-v2-cosine-v0"
HYBRID_ID = "hybrid-bm25-minilm-rrf-v0"
MODEL_REVISION = "8b3219a92973c328a8e22fadcfa821b5dc75636a"
OTHER_REVISION = "0123456789abcdef0123456789abcdef01234567"

SPARSE_CONFIG = {
    "retriever_id": SPARSE_ID,
    "parameters": {"k1": 1.5, "b": 0.75},
}

DENSE_CONFIG = {
    "retriever_id": DENSE_ID,
    "parameters": {
        "embedding_backend": "sentence-transformers",
        "embedding_backend_version": "6.1.0",
        "model_name": "sentence-transformers/all-MiniLM-L6-v2",
        "model_revision": MODEL_REVISION,
        "similarity": "cosine",
        "normalize_embeddings": True,
        "expected_dimension": 384,
    },
}

_BASE_PARAMETERS = {
    "top_k": 3,
    "corpus_id": "commercebench-dev-corpus",
    "corpus_version": "0.1",
    "sparse": SPARSE_CONFIG,
    "dense": DENSE_CONFIG,
    "fusion_method": "rrf",
    "rrf_k": 60,
    "component_top_k": 10,
}


def _corpus(*documents: tuple) -> Corpus:
    return Corpus(
        corpus_id="c",
        corpus_version="1",
        documents=tuple(
            Document(document_id=document_id, text=text)
            for document_id, text in documents
        ),
    )


class StubRetriever:
    """Deterministic Retriever: fixed ranking that honors top_k."""

    retriever_version = "0.1"

    def __init__(self, retriever_id, document_ids, scores=None):
        self.retriever_id = retriever_id
        self._document_ids = tuple(document_ids)
        self._scores = (
            tuple(scores)
            if scores is not None
            else tuple(
                float(len(document_ids) - i)
                for i in range(len(document_ids))
            )
        )
        self.calls = []

    def retrieve(self, query, corpus, top_k):
        self.calls.append(
            {"query": query, "corpus": corpus, "top_k": top_k}
        )
        document_ids = self._document_ids[:top_k]
        return RetrievalResult(
            query=query,
            document_ids=document_ids,
            scores=self._scores[: len(document_ids)],
        )


def _stub(retriever_id, *document_ids, **kwargs):
    return StubRetriever(retriever_id, document_ids, **kwargs)


def _hybrid(sparse=None, dense=None, **kwargs) -> HybridRRFRetriever:
    """HybridRRFRetriever wired to stub components by retriever_id."""
    components = {
        SPARSE_ID: (
            sparse if sparse is not None else _stub(SPARSE_ID)
        ),
        DENSE_ID: dense if dense is not None else _stub(DENSE_ID),
    }
    return HybridRRFRetriever(
        sparse=copy.deepcopy(SPARSE_CONFIG),
        dense=copy.deepcopy(DENSE_CONFIG),
        component_factory=lambda config: components[config.retriever_id],
        **kwargs,
    )


def _base_parameters() -> dict:
    return copy.deepcopy(_BASE_PARAMETERS)


def _hybrid_manifest(parameters: dict) -> ExperimentManifest:
    return ExperimentManifest(
        schema_version=SCHEMA_VERSION,
        experiment_id="exp",
        experiment_name="exp",
        benchmark_version="commercebench-dev-0.1",
        case_ids=("rag-coupon-001",),
        system_id="deterministic-rag",
        system_version="0.1",
        model=None,
        retrieval=RetrievalConfig(
            retriever_id=HYBRID_ID, parameters=parameters
        ),
        memory=None,
        evaluator_id="deterministic-rag-v0",
        evaluator_version="0.1",
        random_seed=0,
        metadata={},
    )


class TestHybridIdentity:
    def test_protocol_and_identity(self):
        retriever = _hybrid()
        assert isinstance(retriever, Retriever)
        assert retriever.retriever_id == "hybrid-bm25-minilm-rrf-v0"
        assert retriever.retriever_version == "0.1"

    def test_component_ids_pinned(self):
        assert HybridRRFRetriever.SPARSE_COMPONENT_ID == (
            BM25Retriever.retriever_id
        )
        assert HybridRRFRetriever.DENSE_COMPONENT_ID == (
            DenseRetriever.retriever_id
        )

    def test_defaults_defined_once(self):
        retriever = _hybrid()
        assert retriever.fusion_method == (
            HybridRRFRetriever.DEFAULT_FUSION_METHOD
        ) == "rrf"
        assert retriever.rrf_k == HybridRRFRetriever.DEFAULT_RRF_K == 60
        assert retriever.component_top_k == (
            HybridRRFRetriever.DEFAULT_COMPONENT_TOP_K
        ) == 10

    def test_algorithm_parameters_declared(self):
        assert set(HybridRRFRetriever.algorithm_parameters) == {
            "sparse",
            "dense",
            "fusion_method",
            "rrf_k",
            "component_top_k",
        }

    def test_registered_in_retriever_registry(self):
        from commercebench.rag import RETRIEVER_REGISTRY

        assert RETRIEVER_REGISTRY[HYBRID_ID] is HybridRRFRetriever


class TestComponentConfigValidation:
    def test_missing_components_rejected(self):
        with pytest.raises(ContractValidationError, match="sparse"):
            HybridRRFRetriever(
                dense=copy.deepcopy(DENSE_CONFIG),
                component_factory=build_retriever,
            )
        with pytest.raises(ContractValidationError, match="dense"):
            HybridRRFRetriever(
                sparse=copy.deepcopy(SPARSE_CONFIG),
                component_factory=build_retriever,
            )

    @pytest.mark.parametrize("value", ["bm25", 3, ["x"], None])
    def test_non_mapping_component_rejected(self, value):
        with pytest.raises(ContractValidationError):
            HybridRRFRetriever(
                sparse=value,
                dense=copy.deepcopy(DENSE_CONFIG),
                component_factory=build_retriever,
            )

    @pytest.mark.parametrize("missing", ["retriever_id", "parameters"])
    def test_component_missing_key_rejected(self, missing):
        sparse = {"retriever_id": SPARSE_ID, "parameters": {"k1": 1.5, "b": 0.75}}
        del sparse[missing]
        with pytest.raises(ContractValidationError, match=missing):
            HybridRRFRetriever(
                sparse=sparse,
                dense=copy.deepcopy(DENSE_CONFIG),
                component_factory=build_retriever,
            )

    def test_component_unknown_key_rejected(self):
        sparse = dict(SPARSE_CONFIG, note="extra")
        with pytest.raises(ContractValidationError, match="unknown"):
            HybridRRFRetriever(
                sparse=sparse,
                dense=copy.deepcopy(DENSE_CONFIG),
                component_factory=build_retriever,
            )

    @pytest.mark.parametrize(
        "bad_id",
        [
            "term-frequency-v0",
            "keyword-match-v0",
            "dense-minilm-l6-v2-cosine-v0",
            "hybrid-bm25-minilm-rrf-v0",
            "bm25",
        ],
    )
    def test_wrong_sparse_component_id_rejected(self, bad_id):
        sparse = {"retriever_id": bad_id, "parameters": {"k1": 1.5, "b": 0.75}}
        with pytest.raises(ContractValidationError, match="sparse"):
            HybridRRFRetriever(
                sparse=sparse,
                dense=copy.deepcopy(DENSE_CONFIG),
                component_factory=build_retriever,
            )

    @pytest.mark.parametrize(
        "bad_id",
        [
            "bm25-okapi-v0",
            "hybrid-bm25-minilm-rrf-v0",
            "term-frequency-v0",
        ],
    )
    def test_wrong_dense_component_id_rejected(self, bad_id):
        dense = {
            "retriever_id": bad_id,
            "parameters": dict(DENSE_CONFIG["parameters"]),
        }
        with pytest.raises(ContractValidationError, match="dense"):
            HybridRRFRetriever(
                sparse=copy.deepcopy(SPARSE_CONFIG),
                dense=dense,
                component_factory=build_retriever,
            )

    def test_nested_hybrid_recursion_rejected(self):
        # A hybrid used as either component would build a recursive
        # graph; the pinned-id check rejects it explicitly.
        nested = {
            "retriever_id": HYBRID_ID,
            "parameters": {},
        }
        with pytest.raises(ContractValidationError):
            HybridRRFRetriever(
                sparse=nested,
                dense=copy.deepcopy(DENSE_CONFIG),
                component_factory=build_retriever,
            )
        with pytest.raises(ContractValidationError):
            HybridRRFRetriever(
                sparse=copy.deepcopy(SPARSE_CONFIG),
                dense=nested,
                component_factory=build_retriever,
            )

    @pytest.mark.parametrize(
        "pipeline_key", ["top_k", "corpus_id", "corpus_version"]
    )
    def test_nested_pipeline_keys_rejected(self, pipeline_key):
        sparse = {
            "retriever_id": SPARSE_ID,
            "parameters": {"k1": 1.5, "b": 0.75, pipeline_key: 3},
        }
        with pytest.raises(ContractValidationError, match="pipeline"):
            HybridRRFRetriever(
                sparse=sparse,
                dense=copy.deepcopy(DENSE_CONFIG),
                component_factory=build_retriever,
            )

    @pytest.mark.parametrize(
        "parameters",
        [
            {"k1": 1.5},
            {"b": 0.75},
            {},
        ],
    )
    def test_incomplete_sparse_parameters_rejected(self, parameters):
        # Every declared component parameter must be explicit — a
        # missing k1/b would silently apply a code default outside the
        # manifest fingerprint.
        sparse = {"retriever_id": SPARSE_ID, "parameters": parameters}
        with pytest.raises(ContractValidationError, match="missing"):
            HybridRRFRetriever(
                sparse=sparse,
                dense=copy.deepcopy(DENSE_CONFIG),
                component_factory=build_retriever,
            )

    @pytest.mark.parametrize(
        "drop_key",
        [
            "embedding_backend",
            "embedding_backend_version",
            "model_name",
            "model_revision",
            "similarity",
            "normalize_embeddings",
            "expected_dimension",
        ],
    )
    def test_incomplete_dense_parameters_rejected(self, drop_key):
        parameters = dict(DENSE_CONFIG["parameters"])
        del parameters[drop_key]
        dense = {"retriever_id": DENSE_ID, "parameters": parameters}
        with pytest.raises(ContractValidationError, match="missing"):
            HybridRRFRetriever(
                sparse=copy.deepcopy(SPARSE_CONFIG),
                dense=dense,
                component_factory=build_retriever,
            )

    @pytest.mark.parametrize(
        "parameters",
        [
            {"k1": 1.5, "b": 0.75, "k11": 1.5},
            {"k1": 1.5, "b": 0.75, "typo": 1},
        ],
    )
    def test_unknown_nested_parameter_rejected(self, parameters):
        sparse = {"retriever_id": SPARSE_ID, "parameters": parameters}
        with pytest.raises(ContractValidationError, match="algorithm"):
            HybridRRFRetriever(
                sparse=sparse,
                dense=copy.deepcopy(DENSE_CONFIG),
                component_factory=build_retriever,
            )

    def test_dense_unknown_nested_parameter_rejected(self):
        parameters = dict(
            DENSE_CONFIG["parameters"], model_revison=MODEL_REVISION
        )
        dense = {"retriever_id": DENSE_ID, "parameters": parameters}
        with pytest.raises(ContractValidationError, match="algorithm"):
            HybridRRFRetriever(
                sparse=copy.deepcopy(SPARSE_CONFIG),
                dense=dense,
                component_factory=build_retriever,
            )

    def test_component_parameters_must_be_mapping(self):
        sparse = {"retriever_id": SPARSE_ID, "parameters": [1.5, 0.75]}
        with pytest.raises(ContractValidationError):
            HybridRRFRetriever(
                sparse=sparse,
                dense=copy.deepcopy(DENSE_CONFIG),
                component_factory=build_retriever,
            )

    def test_factory_returning_non_retriever_rejected(self):
        with pytest.raises(ContractValidationError):
            HybridRRFRetriever(
                sparse=copy.deepcopy(SPARSE_CONFIG),
                dense=copy.deepcopy(DENSE_CONFIG),
                component_factory=lambda config: object(),
            )

    def test_factory_component_id_mismatch_rejected(self):
        # The constructed component must match the configured identity:
        # a factory returning a different retriever would make the
        # runtime disagree with the fingerprint.
        other = _stub("term-frequency-v0", "d-x")
        with pytest.raises(ContractValidationError, match="does not match"):
            HybridRRFRetriever(
                sparse=copy.deepcopy(SPARSE_CONFIG),
                dense=copy.deepcopy(DENSE_CONFIG),
                component_factory=lambda config: other,
            )


class TestFusionConfigValidation:
    @pytest.mark.parametrize(
        "value", ["weighted", "RRF", "", "score", None, 0]
    )
    def test_unsupported_fusion_method_rejected(self, value):
        with pytest.raises(ContractValidationError):
            _hybrid(fusion_method=value)

    @pytest.mark.parametrize(
        "value", [0, -1, -60, True, False, "60", 1.5, None, float("nan")]
    )
    def test_invalid_rrf_k_rejected(self, value):
        with pytest.raises(ContractValidationError):
            _hybrid(rrf_k=value)

    @pytest.mark.parametrize(
        "value", [0, -1, True, False, "10", 2.5, None]
    )
    def test_invalid_component_top_k_rejected(self, value):
        with pytest.raises(ContractValidationError):
            _hybrid(component_top_k=value)

    def test_positive_values_accepted(self):
        retriever = _hybrid(rrf_k=1, component_top_k=1)
        assert retriever.rrf_k == 1
        assert retriever.component_top_k == 1


class TestComponentDepthConstraint:
    def test_final_top_k_above_component_top_k_rejected(self):
        retriever = _hybrid(component_top_k=3)
        corpus = _corpus(("d-a", "match"))
        with pytest.raises(ContractValidationError, match="top_k"):
            retriever.retrieve("match", corpus, top_k=4)

    def test_final_top_k_equal_component_top_k_allowed(self):
        sparse = _stub(SPARSE_ID, "d-a", "d-b", "d-c")
        retriever = _hybrid(sparse=sparse, component_top_k=3)
        corpus = _corpus(("d-a", "x"), ("d-b", "y"), ("d-c", "z"))
        result = retriever.retrieve("q", corpus, top_k=3)
        assert len(result.document_ids) == 3


class TestRRFExactMath:
    """Hand-computed fixture from the Phase 1G spec (rrf_k = 10).

    Sparse: d1 rank1, d2 rank2, d3 rank3
    Dense:  d2 rank1, d4 rank2, d1 rank3

        d1 = 1/11 + 1/13 = 0.16783216783216784
        d2 = 1/12 + 1/11 = 0.17424242424242425
        d3 = 1/13        = 0.07692307692307693
        d4 = 1/12        = 0.08333333333333333
    """

    def _retriever(self):
        return _hybrid(
            sparse=_stub(SPARSE_ID, "d1", "d2", "d3"),
            dense=_stub(DENSE_ID, "d2", "d4", "d1"),
            rrf_k=10,
            component_top_k=10,
        )

    def test_exact_fused_scores(self):
        corpus = _corpus(
            ("d1", "a"), ("d2", "b"), ("d3", "c"), ("d4", "d")
        )
        result = self._retriever().retrieve("q", corpus, top_k=4)
        assert result.document_ids == ("d2", "d1", "d4", "d3")
        assert result.scores == pytest.approx(
            (
                0.17424242424242425,
                0.16783216783216784,
                0.08333333333333333,
                0.07692307692307693,
            )
        )

    def test_fused_scores_match_hand_formula(self):
        corpus = _corpus(
            ("d1", "a"), ("d2", "b"), ("d3", "c"), ("d4", "d")
        )
        result = self._retriever().retrieve("q", corpus, top_k=4)
        scores = dict(zip(result.document_ids, result.scores))
        assert scores["d1"] == pytest.approx(1.0 / 11 + 1.0 / 13)
        assert scores["d2"] == pytest.approx(1.0 / 12 + 1.0 / 11)
        assert scores["d3"] == pytest.approx(1.0 / 13)
        assert scores["d4"] == pytest.approx(1.0 / 12)

    def test_fused_scores_are_rrf_not_component_scores(self):
        # Stub raw scores are large (10..1); fused scores must be the
        # small reciprocal-rank sums, never raw component scores.
        sparse = _stub(
            SPARSE_ID, "d1", "d2", scores=(9.0, 8.0)
        )
        corpus = _corpus(("d1", "a"), ("d2", "b"))
        result = _hybrid(
            sparse=sparse, rrf_k=10
        ).retrieve("q", corpus, top_k=2)
        assert result.scores == pytest.approx((1.0 / 11, 1.0 / 12))
        assert all(score < 1.0 for score in result.scores)


class TestRRFOrderingSemantics:
    def test_tie_break_by_document_id(self):
        # Symmetric ranks -> identical RRF scores -> document_id asc.
        retriever = _hybrid(
            sparse=_stub(SPARSE_ID, "d-a", "d-b"),
            dense=_stub(DENSE_ID, "d-b", "d-a"),
            rrf_k=10,
        )
        corpus = _corpus(("d-a", "x"), ("d-b", "y"))
        result = retriever.retrieve("q", corpus, top_k=2)
        assert result.document_ids == ("d-a", "d-b")
        assert result.scores == pytest.approx(
            (1.0 / 11 + 1.0 / 12, 1.0 / 11 + 1.0 / 12)
        )

    def test_document_only_in_one_component(self):
        # Absent from a component -> zero contribution from it.
        retriever = _hybrid(
            sparse=_stub(SPARSE_ID, "d1", "d2"),
            dense=_stub(DENSE_ID, "d2"),
            rrf_k=60,
            component_top_k=10,
        )
        corpus = _corpus(("d1", "a"), ("d2", "b"))
        result = retriever.retrieve("q", corpus, top_k=2)
        scores = dict(zip(result.document_ids, result.scores))
        assert scores["d1"] == pytest.approx(1.0 / 61)
        assert scores["d2"] == pytest.approx(1.0 / 62 + 1.0 / 61)
        assert result.document_ids == ("d2", "d1")

    def test_duplicate_across_components_merged_once(self):
        retriever = _hybrid(
            sparse=_stub(SPARSE_ID, "d1", "d2"),
            dense=_stub(DENSE_ID, "d1", "d3"),
            rrf_k=10,
        )
        corpus = _corpus(("d1", "a"), ("d2", "b"), ("d3", "c"))
        result = retriever.retrieve("q", corpus, top_k=3)
        assert result.document_ids.count("d1") == 1
        assert len(result.document_ids) == len(set(result.document_ids))
        scores = dict(zip(result.document_ids, result.scores))
        assert scores["d1"] == pytest.approx(1.0 / 11 + 1.0 / 11)

    def test_duplicate_within_component_counts_once(self):
        # A misbehaving component repeating an id contributes only the
        # first (best) rank for that document.
        sparse = StubRetriever(
            SPARSE_ID, ("d1", "d1", "d2"), scores=(5.0, 4.0, 3.0)
        )
        retriever = _hybrid(sparse=sparse, rrf_k=10)
        corpus = _corpus(("d1", "a"), ("d2", "b"))
        result = retriever.retrieve("q", corpus, top_k=3)
        scores = dict(zip(result.document_ids, result.scores))
        assert scores["d1"] == pytest.approx(1.0 / 11)
        assert scores["d2"] == pytest.approx(1.0 / 13)
        assert len(result.document_ids) == 2

    def test_component_rank_uses_position_not_raw_score(self):
        # The stub's raw scores say d-b > d-a but its ranking puts d-a
        # first; RRF must use position (1-based rank), never raw score.
        sparse = _stub(SPARSE_ID, "d-a", "d-b", scores=(0.1, 9.9))
        retriever = _hybrid(sparse=sparse, rrf_k=10)
        corpus = _corpus(("d-a", "x"), ("d-b", "y"))
        result = retriever.retrieve("q", corpus, top_k=2)
        assert result.document_ids == ("d-a", "d-b")
        assert result.scores == pytest.approx((1.0 / 11, 1.0 / 12))

    def test_final_top_k_truncates_fused_list(self):
        retriever = _hybrid(
            sparse=_stub(SPARSE_ID, "d1", "d2", "d3"),
            dense=_stub(DENSE_ID, "d4", "d5"),
            rrf_k=10,
            component_top_k=10,
        )
        corpus = _corpus(
            ("d1", "a"), ("d2", "b"), ("d3", "c"),
            ("d4", "d"), ("d5", "e"),
        )
        result = retriever.retrieve("q", corpus, top_k=2)
        assert len(result.document_ids) == 2
        assert list(result.scores) == sorted(result.scores, reverse=True)


class TestComponentInvocation:
    def test_identical_inputs_reach_both_components(self):
        sparse = _stub(SPARSE_ID, "d-a")
        dense = _stub(DENSE_ID, "d-b")
        retriever = _hybrid(
            sparse=sparse, dense=dense, component_top_k=7
        )
        corpus = _corpus(("d-a", "x"), ("d-b", "y"))
        retriever.retrieve("Raw Query TEXT", corpus, top_k=3)
        for component in (sparse, dense):
            (call,) = component.calls
            assert call["query"] == "Raw Query TEXT"
            assert call["corpus"] is corpus
            assert call["top_k"] == 7

    def test_component_top_k_reaches_component_runtime(self):
        sparse = _stub(SPARSE_ID, "d-a")
        dense = _stub(DENSE_ID, "d-b")
        retriever = _hybrid(
            sparse=sparse, dense=dense, component_top_k=5
        )
        corpus = _corpus(("d-a", "x"), ("d-b", "y"))
        retriever.retrieve("q", corpus, top_k=2)
        assert sparse.calls[0]["top_k"] == 5
        assert dense.calls[0]["top_k"] == 5

    def test_rrf_k_reaches_fusion_runtime(self):
        # rrf_k is fingerprinted AND changes the fused scores — not a
        # fingerprinted-but-ignored parameter.
        sparse = _stub(SPARSE_ID, "d1", "d2")
        corpus = _corpus(("d1", "a"), ("d2", "b"))
        by_k = {}
        for rrf_k in (10, 60):
            retriever = _hybrid(
                sparse=StubRetriever(SPARSE_ID, ("d1", "d2")),
                rrf_k=rrf_k,
            )
            by_k[rrf_k] = retriever.retrieve("q", corpus, top_k=2).scores
        assert by_k[10] == pytest.approx((1.0 / 11, 1.0 / 12))
        assert by_k[60] == pytest.approx((1.0 / 61, 1.0 / 62))
        assert by_k[10] != by_k[60]


class TestCandidateDepth:
    """component_top_k controls the real fusion candidate pool.

    Real BM25 component: on this corpus the query "match" ranks
    d-1 > d-2 > d-3 > d-rel (BM25 score>0 policy drops "d-x").
    """

    _DOCS = (
        ("d-1", "match match match match"),
        ("d-2", "match match match"),
        ("d-3", "match match"),
        ("d-rel", "match"),
        ("d-x", "unrelated"),
    )

    def test_bm25_baseline_ranking_for_fixture(self):
        corpus = _corpus(*self._DOCS)
        result = BM25Retriever().retrieve("match", corpus, top_k=5)
        assert result.document_ids == ("d-1", "d-2", "d-3", "d-rel")

    def test_shallow_depth_excludes_relevant_candidate(self):
        corpus = _corpus(*self._DOCS)
        dense = _stub(DENSE_ID)
        retriever = _hybrid(
            sparse=BM25Retriever(), dense=dense, component_top_k=3
        )
        result = retriever.retrieve("match", corpus, top_k=3)
        assert result.document_ids == ("d-1", "d-2", "d-3")
        assert "d-rel" not in result.document_ids
        assert dense.calls[0]["top_k"] == 3

    def test_deeper_depth_admits_relevant_candidate(self):
        corpus = _corpus(*self._DOCS)
        dense = _stub(DENSE_ID)
        retriever = _hybrid(
            sparse=BM25Retriever(), dense=dense, component_top_k=5
        )
        result = retriever.retrieve("match", corpus, top_k=4)
        assert result.document_ids == ("d-1", "d-2", "d-3", "d-rel")
        assert dense.calls[0]["top_k"] == 5
        # The candidate depth also shows in diagnostics.
        components = retriever.runtime_metadata()["hybrid"]["components"]
        assert components["sparse"]["document_ids"] == [
            "d-1", "d-2", "d-3", "d-rel"
        ]


class TestDiagnosticsAndSingleEvent:
    def _case(self, relevant=()) -> CaseSpec:
        return CaseSpec(
            schema_version=SCHEMA_VERSION,
            case_id="case-1",
            benchmark_version="commercebench-dev-0.1",
            task_family="grounded_qa",
            intent="return",
            difficulty=Difficulty.EASY,
            conversation_type=ConversationType.SINGLE_TURN,
            answerability=Answerability.ANSWERABLE,
            user_input="q",
            required_facts=(),
            forbidden_claims=(),
            relevant_document_ids=tuple(relevant),
            metadata={},
        )

    def _manifest(self) -> ExperimentManifest:
        return ExperimentManifest(
            schema_version=SCHEMA_VERSION,
            experiment_id="exp",
            experiment_name="exp",
            benchmark_version="commercebench-dev-0.1",
            case_ids=("case-1",),
            system_id="deterministic-rag",
            system_version="0.1",
            retrieval=RetrievalConfig(retriever_id=HYBRID_ID),
            evaluator_id="deterministic-rag-v0",
            evaluator_version="0.1",
            metadata={},
        )

    def test_exactly_one_retrieval_event_component_ids_in_metadata(self):
        sparse = _stub(SPARSE_ID, "d-s1", "d-s2", "d-s3")
        dense = _stub(DENSE_ID, "d-d1", "d-d2", "d-d3")
        retriever = _hybrid(
            sparse=sparse, dense=dense, rrf_k=60, component_top_k=3
        )
        corpus = _corpus(
            ("d-s1", "a"), ("d-s2", "b"), ("d-s3", "c"),
            ("d-d1", "d"), ("d-d2", "e"), ("d-d3", "f"),
        )
        pipeline = DeterministicRAGPipeline(
            retriever=retriever,
            corpus=corpus,
            top_k=2,
            answer_by_document_id={"d-d1": "answer-d-d1"},
        )
        system = DeterministicRAGSystem(pipeline=pipeline)
        trace = run_case(self._case(), self._manifest(), system)

        # Exactly one event — the fused ranking only.
        assert len(trace.retrieval_events) == 1
        event = trace.retrieval_events[0]
        assert event.document_ids == ("d-d1", "d-s1")
        assert event.scores == pytest.approx((1.0 / 61, 1.0 / 61))
        assert trace.output_text == "answer-d-d1"

        # Component rankings live in runtime_metadata, not in events.
        metadata = trace.runtime_metadata
        assert metadata["retriever_id"] == HYBRID_ID
        assert metadata["retriever_version"] == "0.1"
        assert metadata["top_k"] == 2
        hybrid_meta = metadata["hybrid"]
        assert hybrid_meta["fusion_method"] == "rrf"
        assert hybrid_meta["rrf_k"] == 60
        assert hybrid_meta["component_top_k"] == 3
        assert hybrid_meta["final_top_k"] == 2
        components = hybrid_meta["components"]
        assert components["sparse"]["retriever_id"] == SPARSE_ID
        assert components["sparse"]["retriever_version"] == "0.1"
        assert components["sparse"]["parameters"] == {
            "k1": 1.5,
            "b": 0.75,
        }
        assert components["sparse"]["document_ids"] == [
            "d-s1", "d-s2", "d-s3"
        ]
        assert components["sparse"]["scores"] == [3.0, 2.0, 1.0]
        assert components["dense"]["retriever_id"] == DENSE_ID
        assert components["dense"]["document_ids"] == [
            "d-d1", "d-d2", "d-d3"
        ]
        # Component-only documents must not leak into the event.
        assert "d-s3" not in event.document_ids
        assert "d-d3" not in event.document_ids

    def test_metrics_consume_fused_ranking_only(self):
        # d-rel is relevant and present in the sparse component ranking
        # but falls outside the fused top_k. If the evaluator ever saw
        # component rankings as extra events, recall would wrongly be
        # non-zero / no RETRIEVAL_MISS.
        sparse = _stub(SPARSE_ID, "d-s1", "d-s2", "d-rel")
        dense = _stub(DENSE_ID, "d-d1", "d-d2", "d-d3")
        retriever = _hybrid(
            sparse=sparse, dense=dense, rrf_k=60, component_top_k=3
        )
        corpus = _corpus(
            ("d-s1", "a"), ("d-s2", "b"), ("d-rel", "r"),
            ("d-d1", "d"), ("d-d2", "e"), ("d-d3", "f"),
        )
        pipeline = DeterministicRAGPipeline(
            retriever=retriever, corpus=corpus, top_k=3
        )
        system = DeterministicRAGSystem(pipeline=pipeline)
        case = self._case(relevant=("d-rel",))
        manifest = self._manifest()
        trace = run_case(case, manifest, system)
        result = DeterministicRAGEvaluator(ks=(1, 3)).evaluate(
            case, trace
        )
        assert result.metrics["retrieval_recall_at_3"].value == 0.0
        assert result.metrics["retrieval_mrr"].value == 0.0
        assert FAILURE_RETRIEVAL_MISS in result.failure_categories
        # And the diagnostic still proves the sparse component saw it.
        assert (
            "d-rel"
            in trace.runtime_metadata["hybrid"]["components"]["sparse"][
                "document_ids"
            ]
        )

    def test_runtime_metadata_json_round_trip(self):
        retriever = _hybrid(
            sparse=_stub(SPARSE_ID, "d-a"),
            dense=_stub(DENSE_ID, "d-b"),
        )
        corpus = _corpus(("d-a", "x"), ("d-b", "y"))
        pipeline = DeterministicRAGPipeline(
            retriever=retriever, corpus=corpus, top_k=1
        )
        trace = run_case(
            self._case(), self._manifest(),
            DeterministicRAGSystem(pipeline=pipeline),
        )
        restored = RunTrace.from_json(trace.to_json())
        assert restored == trace

    def test_dense_component_runtime_identity_tracked(self):
        # A real DenseRetriever on a fake encoder exposes model identity
        # through the hybrid diagnostics under components.dense.runtime.
        vectors = {
            "q": [1.0, 0.0],
            "text-a": [1.0, 0.0],
            "text-b": [0.0, 1.0],
        }

        def factory(**kwargs):
            class _Fake:
                dimension = 2

                def encode(self, texts):
                    return [list(vectors[t]) for t in texts]

            return _Fake()

        dense = DenseRetriever(
            expected_dimension=2, encoder_factory=factory
        )
        retriever = _hybrid(
            sparse=_stub(SPARSE_ID, "d-a"), dense=dense
        )
        corpus = _corpus(("d-a", "text-a"), ("d-b", "text-b"))
        retriever.retrieve("q", corpus, top_k=2)
        dense_meta = retriever.runtime_metadata()["hybrid"]["components"][
            "dense"
        ]
        assert dense_meta["retriever_id"] == DENSE_ID
        assert dense_meta["parameters"]["model_revision"] == MODEL_REVISION
        assert dense_meta["runtime"]["model_name"] == (
            "sentence-transformers/all-MiniLM-L6-v2"
        )
        assert dense_meta["runtime"]["model_revision"] == MODEL_REVISION
        assert dense_meta["runtime"]["similarity"] == "cosine"
        assert dense_meta["runtime"]["embedding_dimension"] == 2


class TestBuildRetrieverPlumbing:
    def test_build_hybrid_via_factory(self):
        retriever = build_retriever(
            RetrievalConfig(
                retriever_id=HYBRID_ID,
                parameters=_base_parameters(),
            )
        )
        assert isinstance(retriever, HybridRRFRetriever)
        assert isinstance(retriever._sparse, BM25Retriever)
        assert retriever._sparse.k1 == 1.5
        assert retriever._sparse.b == 0.75
        assert isinstance(retriever._dense, DenseRetriever)
        assert retriever._dense.model_revision == MODEL_REVISION
        # Construction stays lazy: the encoder exists but no model.
        assert isinstance(
            retriever._dense._encoder, SentenceTransformerEncoder
        )
        assert retriever._dense._encoder._model is None
        assert retriever.rrf_k == 60
        assert retriever.component_top_k == 10
        assert retriever.fusion_method == "rrf"

    def test_nested_component_config_reaches_component_runtime(self):
        parameters = _base_parameters()
        parameters["sparse"]["parameters"]["k1"] = 2.0
        retriever = build_retriever(
            RetrievalConfig(retriever_id=HYBRID_ID, parameters=parameters)
        )
        assert retriever._sparse.k1 == 2.0
        assert retriever._dense.normalize_embeddings is True

    @pytest.mark.parametrize(
        "parameters",
        [
            {"rrf_kk": 60},
            {"component_topk": 10},
            {"sparse_retriver": SPARSE_CONFIG},
            {"fusion_methd": "rrf"},
        ],
    )
    def test_unknown_top_level_parameter_rejected(self, parameters):
        merged = _base_parameters()
        merged.update(parameters)
        with pytest.raises(ContractValidationError, match="algorithm"):
            build_retriever(
                RetrievalConfig(
                    retriever_id=HYBRID_ID, parameters=merged
                )
            )

    def test_pipeline_keys_filtered_before_components(self):
        # top_k/corpus_id/corpus_version are pipeline-owned: they must
        # not leak into component parameter validation.
        retriever = build_retriever(
            RetrievalConfig(
                retriever_id=HYBRID_ID,
                parameters=_base_parameters(),
            )
        )
        assert "top_k" not in retriever._sparse_config.parameters
        assert "corpus_id" not in retriever._dense_config.parameters

    def test_from_manifest_builds_without_loading_model(
        self, hybrid_manifest, rag_corpus, rag_answers
    ):
        system = DeterministicRAGSystem.from_manifest(
            hybrid_manifest, rag_corpus, rag_answers
        )
        assert system.system_id == "deterministic-rag"

    def test_corpus_id_mismatch_rejected(
        self, hybrid_manifest, rag_answers
    ):
        other = Corpus(
            corpus_id="other-corpus",
            corpus_version="0.1",
            documents=(Document(document_id="x", text="y"),),
        )
        with pytest.raises(ContractValidationError, match="corpus_id"):
            DeterministicRAGSystem.from_manifest(
                hybrid_manifest, other, rag_answers
            )


class TestHybridFingerprint:
    def test_same_config_same_fingerprint(self):
        first = _hybrid_manifest(_base_parameters()).config_fingerprint()
        second = _hybrid_manifest(_base_parameters()).config_fingerprint()
        assert first == second

    @pytest.mark.parametrize(
        "mutate",
        [
            lambda p: p["sparse"]["parameters"].update(k1=1.2),
            lambda p: p["sparse"]["parameters"].update(b=0.5),
            lambda p: p["dense"]["parameters"].update(
                model_name="other/model"
            ),
            lambda p: p["dense"]["parameters"].update(
                model_revision=OTHER_REVISION
            ),
            lambda p: p["dense"]["parameters"].update(similarity="dot"),
            lambda p: p["dense"]["parameters"].update(
                normalize_embeddings=False
            ),
            lambda p: p["dense"]["parameters"].update(
                embedding_backend_version="6.2.0"
            ),
            lambda p: p.update(fusion_method="other"),
            lambda p: p.update(rrf_k=61),
            lambda p: p.update(component_top_k=5),
            lambda p: p.update(top_k=5),
            lambda p: p.update(corpus_version="0.2"),
            lambda p: p["sparse"].update(
                retriever_id="term-frequency-v0"
            ),
        ],
    )
    def test_result_affecting_change_changes_fingerprint(self, mutate):
        changed = _base_parameters()
        mutate(changed)
        assert _hybrid_manifest(_base_parameters()).config_fingerprint() != (
            _hybrid_manifest(changed).config_fingerprint()
        )

    def test_hybrid_differs_from_component_fingerprints(
        self, bm25_manifest, dense_manifest, hybrid_manifest
    ):
        fingerprints = {
            bm25_manifest.config_fingerprint(),
            dense_manifest.config_fingerprint(),
            hybrid_manifest.config_fingerprint(),
        }
        assert len(fingerprints) == 3


class TestHybridManifest:
    def test_manifest_declares_full_component_identity(
        self, hybrid_manifest
    ):
        retrieval = hybrid_manifest.retrieval
        assert retrieval.retriever_id == HYBRID_ID
        parameters = retrieval.parameters
        assert parameters["top_k"] == 3
        assert parameters["corpus_id"] == "commercebench-dev-corpus"
        assert parameters["corpus_version"] == "0.1"
        assert parameters["fusion_method"] == "rrf"
        assert parameters["rrf_k"] == 60
        assert parameters["component_top_k"] == 10
        assert parameters["sparse"] == {
            "retriever_id": "bm25-okapi-v0",
            "parameters": {"k1": 1.5, "b": 0.75},
        }
        dense = parameters["dense"]
        assert dense["retriever_id"] == DENSE_ID
        assert dense["parameters"]["model_name"] == (
            "sentence-transformers/all-MiniLM-L6-v2"
        )
        assert dense["parameters"]["model_revision"] == MODEL_REVISION
        assert dense["parameters"]["similarity"] == "cosine"
        assert dense["parameters"]["normalize_embeddings"] is True
        assert dense["parameters"]["expected_dimension"] == 384

    def test_same_case_list_as_component_manifests(
        self, bm25_manifest, dense_manifest, hybrid_manifest
    ):
        assert bm25_manifest.case_ids == dense_manifest.case_ids == (
            hybrid_manifest.case_ids
        )
        assert len(hybrid_manifest.case_ids) == 11


class TestControlledComparison:
    """BM25 / Dense / Hybrid: same everything except retrieval config."""

    def test_only_retrieval_configuration_differs(
        self, bm25_manifest, dense_manifest, hybrid_manifest
    ):
        for field in (
            "benchmark_version",
            "case_ids",
            "system_id",
            "system_version",
            "model",
            "memory",
            "evaluator_id",
            "evaluator_version",
            "random_seed",
        ):
            assert getattr(bm25_manifest, field) == getattr(
                hybrid_manifest, field
            ) == getattr(dense_manifest, field)
        ids = {
            bm25_manifest.retrieval.retriever_id,
            dense_manifest.retrieval.retriever_id,
            hybrid_manifest.retrieval.retriever_id,
        }
        assert ids == {SPARSE_ID, DENSE_ID, HYBRID_ID}

    def test_hybrid_recovers_dense_hit_when_bm25_misses(
        self, rag_corpus, rag_cases
    ):
        # On the refund-miss case the query shares no development
        # tokens with the corpus: real BM25 returns nothing, and the
        # fused ranking is entirely the dense component's. This is an
        # observed fixture behavior, not a benchmark conclusion.
        case = rag_cases["rag-refund-miss-001"]
        dense = _stub(
            DENSE_ID,
            "policy-refund-001",
            "policy-return-001",
            "policy-exchange-001",
        )
        hybrid = _hybrid(sparse=BM25Retriever(), dense=dense)
        result = hybrid.retrieve(
            case.user_input, rag_corpus, top_k=3
        )
        bm25_alone = BM25Retriever().retrieve(
            case.user_input, rag_corpus, top_k=3
        )
        assert bm25_alone.document_ids == ()
        assert result.document_ids == (
            "policy-refund-001",
            "policy-return-001",
            "policy-exchange-001",
        )
        components = hybrid.runtime_metadata()["hybrid"]["components"]
        assert components["sparse"]["document_ids"] == []
        assert components["dense"]["document_ids"][0] == (
            "policy-refund-001"
        )

    def test_rrf_union_outranks_sparse_only_result(self):
        # A doc both components rank beats docs only one component saw.
        retriever = _hybrid(
            sparse=_stub(SPARSE_ID, "d-shared", "d-sparse"),
            dense=_stub(DENSE_ID, "d-dense", "d-shared"),
            rrf_k=10,
        )
        corpus = _corpus(
            ("d-shared", "a"), ("d-sparse", "b"), ("d-dense", "c")
        )
        result = retriever.retrieve("q", corpus, top_k=3)
        assert result.document_ids[0] == "d-shared"


class TestEdgeCases:
    def test_empty_corpus_returns_empty(self):
        corpus = Corpus(corpus_id="c", corpus_version="1", documents=())
        result = _hybrid().retrieve("q", corpus, top_k=3)
        assert result.document_ids == ()
        assert result.scores == ()

    def test_both_components_empty_returns_empty(self):
        corpus = _corpus(("d-a", "x"))
        result = _hybrid().retrieve("q", corpus, top_k=3)
        assert result.document_ids == ()
        assert result.scores == ()

    def test_sparse_empty_uses_dense_ranking(self):
        retriever = _hybrid(
            dense=_stub(DENSE_ID, "d-a", "d-b"), rrf_k=10
        )
        corpus = _corpus(("d-a", "x"), ("d-b", "y"))
        result = retriever.retrieve("q", corpus, top_k=2)
        assert result.document_ids == ("d-a", "d-b")
        assert result.scores == pytest.approx((1.0 / 11, 1.0 / 12))

    def test_deterministic_repeated_runs(self):
        retriever = _hybrid(
            sparse=_stub(SPARSE_ID, "d-a", "d-c"),
            dense=_stub(DENSE_ID, "d-b", "d-a"),
            rrf_k=10,
        )
        corpus = _corpus(
            ("d-a", "x"), ("d-b", "y"), ("d-c", "z")
        )
        first = retriever.retrieve("q", corpus, top_k=3)
        second = retriever.retrieve("q", corpus, top_k=3)
        assert first == second

    @pytest.mark.parametrize("query", ["", None, 3])
    def test_invalid_query_rejected(self, query):
        corpus = _corpus(("d-a", "x"))
        with pytest.raises(ContractValidationError):
            _hybrid().retrieve(query, corpus, top_k=3)

    @pytest.mark.parametrize("top_k", [0, -1, 2.5, "3", None, True])
    def test_invalid_top_k_rejected(self, top_k):
        corpus = _corpus(("d-a", "x"))
        with pytest.raises(ContractValidationError):
            _hybrid().retrieve("q", corpus, top_k=top_k)

    def test_non_corpus_rejected(self):
        with pytest.raises(ContractValidationError):
            _hybrid().retrieve("q", {"documents": []}, top_k=3)

    def test_component_returning_non_result_rejected(self):
        class BadComponent:
            retriever_id = SPARSE_ID
            retriever_version = "0.1"

            def retrieve(self, query, corpus, top_k):
                return ("d-a",)

        retriever = _hybrid(sparse=BadComponent())
        corpus = _corpus(("d-a", "x"))
        with pytest.raises(ContractValidationError):
            retriever.retrieve("q", corpus, top_k=1)


class TestFreshProcessRegistration:
    def test_registry_survives_fresh_import(self):
        # Importing commercebench.rag in a clean interpreter must
        # self-register every retriever: a future __init__ edit that
        # dropped the dense/hybrid import would fail here.
        code = """
from commercebench.rag import RETRIEVER_REGISTRY, build_retriever
from commercebench.contracts.experiment import RetrievalConfig

expected = {
    'keyword-match-v0',
    'term-frequency-v0',
    'bm25-okapi-v0',
    'dense-minilm-l6-v2-cosine-v0',
    'hybrid-bm25-minilm-rrf-v0',
}
assert expected <= set(RETRIEVER_REGISTRY), set(RETRIEVER_REGISTRY)

dense = build_retriever(
    RetrievalConfig(retriever_id='dense-minilm-l6-v2-cosine-v0'))
hybrid = build_retriever(RetrievalConfig(
    retriever_id='hybrid-bm25-minilm-rrf-v0',
    parameters={
        'sparse': {
            'retriever_id': 'bm25-okapi-v0',
            'parameters': {'k1': 1.5, 'b': 0.75},
        },
        'dense': {
            'retriever_id': 'dense-minilm-l6-v2-cosine-v0',
            'parameters': {
                'embedding_backend': 'sentence-transformers',
                'embedding_backend_version': '6.1.0',
                'model_name': 'sentence-transformers/all-MiniLM-L6-v2',
                'model_revision':
                    '8b3219a92973c328a8e22fadcfa821b5dc75636a',
                'similarity': 'cosine',
                'normalize_embeddings': True,
                'expected_dimension': 384,
            },
        },
        'fusion_method': 'rrf',
        'rrf_k': 60,
        'component_top_k': 10,
    }))
assert dense.retriever_id == 'dense-minilm-l6-v2-cosine-v0'
assert hybrid.retriever_id == 'hybrid-bm25-minilm-rrf-v0'
assert hybrid._sparse.retriever_id == 'bm25-okapi-v0'
assert hybrid._dense.retriever_id == 'dense-minilm-l6-v2-cosine-v0'
assert hybrid._dense._encoder._model is None
print('fresh-registry-ok')
"""
        result = subprocess.run(
            [sys.executable, "-c", code],
            capture_output=True,
            text=True,
        )
        assert result.returncode == 0, result.stderr
        assert "fresh-registry-ok" in result.stdout
