"""Core V0 contracts: CaseSpec, ExperimentManifest, RunTrace, EvaluationResult."""

from .case import (
    Answerability,
    CaseSpec,
    ConversationType,
    Difficulty,
)
from .common import SCHEMA_VERSION
from .dialogue import (
    DialogueCaseSpec,
    DialogueHistoryEntry,
    DialogueRunTrace,
    DialogueStepTrace,
    DialogueToolDescriptor,
    DialogueTurnInput,
    DialogueTurnOutput,
    DialogueTurnSpec,
    DialogueTurnTrace,
    ExpectedToolCall,
    HISTORY_ROLES,
    TERMINATION_COMPLETED,
    TERMINATION_INVALID_TOOL,
    TERMINATION_MAX_TURNS,
    TERMINATION_REASONS,
    TERMINATION_SYSTEM_ERROR,
    TERMINATION_TOOL_LIMIT,
    TERMINATION_USER_DONE,
)
from .errors import ContractValidationError
from .evaluation import EvaluationResult, MetricResult
from .experiment import (
    DialogueHarnessConfig,
    ExperimentManifest,
    MemoryConfig,
    ModelConfig,
    RerankerConfig,
    RetrievalConfig,
)
from .trace import (
    MemoryEvent,
    RetrievalEvent,
    RetrievalRole,
    RunTrace,
    ToolEvent,
    UsageStats,
)

__all__ = [
    "SCHEMA_VERSION",
    "Answerability",
    "CaseSpec",
    "ContractValidationError",
    "ConversationType",
    "DialogueCaseSpec",
    "DialogueHarnessConfig",
    "DialogueHistoryEntry",
    "DialogueRunTrace",
    "DialogueStepTrace",
    "DialogueToolDescriptor",
    "DialogueTurnInput",
    "DialogueTurnOutput",
    "DialogueTurnSpec",
    "DialogueTurnTrace",
    "Difficulty",
    "EvaluationResult",
    "ExpectedToolCall",
    "ExperimentManifest",
    "HISTORY_ROLES",
    "MemoryConfig",
    "MemoryEvent",
    "MetricResult",
    "ModelConfig",
    "RerankerConfig",
    "RetrievalConfig",
    "RetrievalEvent",
    "RetrievalRole",
    "RunTrace",
    "TERMINATION_COMPLETED",
    "TERMINATION_INVALID_TOOL",
    "TERMINATION_MAX_TURNS",
    "TERMINATION_REASONS",
    "TERMINATION_SYSTEM_ERROR",
    "TERMINATION_TOOL_LIMIT",
    "TERMINATION_USER_DONE",
    "ToolEvent",
    "UsageStats",
]
